// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/api/middleware.ts";
import * as $3 from "./routes/api/post.ts";
import * as $4 from "./routes/api/profile.ts";
import * as $5 from "./routes/api/sign-in.ts";
import * as $6 from "./routes/api/sign-up.ts";
import * as $7 from "./routes/board.tsx";
import * as $8 from "./routes/index.tsx";
import * as $9 from "./routes/profile.tsx";
import * as $10 from "./routes/signin.tsx";
import * as $11 from "./routes/signup.tsx";
import * as $$0 from "./islands/Board.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/Menu.tsx";
import * as $$3 from "./islands/Profile.tsx";
import * as $$4 from "./islands/Signin.tsx";
import * as $$5 from "./islands/Signup.tsx";
import * as $$6 from "./islands/Signup2.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/api/middleware.ts": $2,
    "./routes/api/post.ts": $3,
    "./routes/api/profile.ts": $4,
    "./routes/api/sign-in.ts": $5,
    "./routes/api/sign-up.ts": $6,
    "./routes/board.tsx": $7,
    "./routes/index.tsx": $8,
    "./routes/profile.tsx": $9,
    "./routes/signin.tsx": $10,
    "./routes/signup.tsx": $11,
  },
  islands: {
    "./islands/Board.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/Menu.tsx": $$2,
    "./islands/Profile.tsx": $$3,
    "./islands/Signin.tsx": $$4,
    "./islands/Signup.tsx": $$5,
    "./islands/Signup2.tsx": $$6,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
